language: ruby
cache: bundler
rvm:
- 2.3.3
- 2.4.1
sudo: false
env:
  - AWS_REGION: us-west-2
deploy:
  provider: rubygems
  gem:
    master: capistrano-asg
  on:
    repo: sixfeetover/capistrano-asg
    branch: master
